# Generated by Django 5.2.5 on 2025-08-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200, verbose_name='Modelo')),
                ('factory_year', models.IntegerField(blank=True, null=True, verbose_name='Ano de fabricação')),
                ('model_year', models.IntegerField(blank=True, null=True, verbose_name='Ano do modelo')),
                ('value', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True, verbose_name='Preço')),
                ('photo', models.ImageField(upload_to='cars/', verbose_name='Foto')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_brand', to='Cars.brand', verbose_name='Marca')),
            ],
        ),
    ]
