# Generated by Django 5.0.7 on 2024-08-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro', '0003_car_value_alter_brand_name_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='midia'),
        ),
    ]
