# Generated by Django 5.0.7 on 2024-08-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro', '0004_car_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='foto',
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
