# Generated by Django 5.0.7 on 2024-08-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro', '0005_remove_car_foto_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='car',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço'),
        ),
    ]
