# Generated by Django 5.0.7 on 2024-08-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro', '0006_alter_car_photo_alter_car_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to='cars/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='car',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True, verbose_name='Preço'),
        ),
    ]
