# Generated by Django 5.0.7 on 2024-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro', '0007_alter_car_photo_alter_car_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=9, null=True, verbose_name='Preço'),
        ),
    ]
